#!/usr/local/bin/python3
try:
    import click_completion
    from mycmds.cli import cli, Command
    import click_completion.core
except ImportError:
    import os
    requirement_path = os.path.join(os.path.dirname(__file__), 'requirements.txt')
    print("Please install the required packages: pip install -r {}".format(requirement_path))
    exit()

@Command(cli)
def completion():
    click_completion.core.install()

if __name__ == '__main__':
    click_completion.init()
    cli()
